### ISSUE TITLE
Why not build a community in this project?

### ISSUE THREAD

**Issue by liankong233** [davxy/beeos#28]
I think this project is very good. At least it is a lightweight kernel, which is very conducive to learning and research. Why doesn't the author plan to set up an open source community for this project?

**Comment by davxy** [comment]
@udochina thank you for your interest. The project started during a period when I was learning OS internals and as a personal project. No ambitions. 

Frankly at the moment I don't plan to work on it personally due to time constraints and a shift on my priorities.
 
Nevertheless, I know that is a good learning instrument and is there for anyone who desire to use it and/or extend it.

Good missing milestones are sockets and a working port to arm (e.g. to run on a raspi).
